name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Release Dir
        run: mkdir -p Release/apk

      # 关键：-x :chaquo: 跳过chaquo模块任务，解决Python3.10缺失
      - name: Build Debug APK
        run: ./gradlew assembleDebug -x :chaquo: --no-daemon -Dgradle.wrapper.validateDistribution=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app/build/outputs/apk/debug/
