name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      # 生成本地SDK配置
      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      # 给gradlew执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 关键：提前创建 Release/apk 目录，避免复制失败
      - name: Create Release Dir
        run: mkdir -p Release/apk

      # 编译正式包
      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon

      # 上传成品（优先取你自定义目录，兼顾原生输出目录）
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            Release/apk/
            app/build/outputs/apk/release/
